server:
  port: 8080
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password: 123456
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 2
    timeout: 5000